### ISSUE TITLE
Visual Studio 2015 RC problem adding existing standard Class Library project and Nuget restore

### ISSUE THREAD

**Issue by radenkozec** [NuGet/NuGet3#15]
After I add existing Class Library project and try to build to restore packages I am getting exception : Error occured:\nSystem.IndexOutOfRangeException: Index was outside the bounds of the array.

Then I close Visual Studio 2015 RC and re-open and package restore then works correctly.

**Comment by yishaigalatzer** [comment]
moved to https://github.com/NuGet/Home/issues/567
