### ISSUE TITLE
Opt-in NuGet support for new project types

### ISSUE THREAD

**Issue by sharwell** [NuGet/NuGet3#16]
I'm working on a Visual Studio extension that includes a new project type. A basic requirement of this extension is that it be distributed as a VSIX and not as a MSI. In order to successfully accomplish this, the project templates included in the extension [install a NuGet package](https://github.com/tunnelvisionlabs/JavaForVS/blob/1.2.0/Templates/Java/ProjectTemplates/JavaClassLibraryProjectTemplate/JavaClassLibrary.vstemplate#L21-L29) which adds the **.targets** file used to build the project.

I am now looking into migrating to using CPS instead of MPFProj to implement the basic project type support in order to address a long list of outstanding MPFProj bugs. Unfortunately, I don't see an easy way in CPS to [opt-in to NuGet support](https://github.com/tunnelvisionlabs/JavaForVS/blob/1.2.0/Tvl.VisualStudio.Language.Java/Project/JavaProjectNode.cs#L62-L67) in a custom project type.

Aside from simply [reusing one of the rarer project type IDs](https://github.com/NuGet/NuGet.VisualStudioExtension/blob/705732d07e8b32cbaa3feeef3564323c5a0f7275/src/PackageManagement.VisualStudio/Utility/EnvDTEProjectUtility.cs#L42-L48) for our project type (a workable but unpleasant solution for users who may want to install both), what can we do to declare support for NuGet in our extension?

**Comment by yishaigalatzer** [comment]
Moved to https://github.com/NuGet/Home/issues/569
